all:	Mapper Reducer Combiner

Mapper: 
	gcc -o Mapper Mapper.c
		  
Reducer: 
	gcc -o Reducer Reducer.c
		  
Combiner: 
	gcc -o Combiner Combiner.c
		  
clean:
	rm -rf mapper reducer combiner
			
		  